---
- name: create /opt/{{project_name}}
  file:
    path: /opt/{{project_name}}
    state: directory
- name: symlink /opt/project_name/current to /home/ec2-user/ocracoke
  file:
    path: /opt/{{project_name}}/current
    src: /home/ec2-user/ocracoke
    state: link
    force: yes
  notify: restart httpd
